"""Writes docs/FEATURES.md: every Settings-page option → the plugin(s) that read it.

    python3 scripts/features.py
"""
import re, os, glob
from html.parser import HTMLParser

class Sections(HTMLParser):
    def __init__(self):
        super().__init__(); self.group = None; self.depth = 0; self.cap = None; self.buf = ''; self.rows = []
    def handle_starttag(self, tag, attrs):
        a = dict(attrs)
        if tag == 'header': self.cap, self.buf = 'header', ''
        elif tag == 'section':
            self.depth += 1
            if self.depth == 1: self.rows.append(dict(group=self.group, title='', new=a.get('new'), ids=[]))
        elif tag == 'div' and a.get('class') == 'title' and self.depth and not self.rows[-1]['title']: self.cap, self.buf = 'title', ''
        elif tag in ('input', 'select', 'textarea') and a.get('id') and self.depth and not a['id'].endswith('-input'): self.rows[-1]['ids'].append(a['id'])
    def handle_endtag(self, tag):
        if tag == 'section': self.depth -= 1
        if self.cap and tag in ('header', 'div'):
            text = re.sub(r'\s+', ' ', self.buf).strip()
            if self.cap == 'header': self.group = text
            else: self.rows[-1]['title'] = text
            self.cap = None
    def handle_data(self, data):
        if self.cap: self.buf += data

parser = Sections(); parser.feed(open('src/settings.html', encoding='utf8').read())

plugins = {}
for path in sorted(glob.glob('src/plugins/**/*.js', recursive=True)):
    if path.endswith('index.js'): continue
    plugins[path[len('src/'):]] = open(path, encoding='utf8').read()
legacy = {f: '\n'.join(l for l in open(f'src/{f}', encoding='utf8').read().split('\n') if 'TTV.run(' not in l) for f in ('tools.js', 'chat.js', 'player.js', 'clips.js', 'background.js')}

def readers(key):
    pattern = re.compile(r'\bSettings\.' + re.escape(key) + r'\b|[\'"`]' + re.escape(key) + r'[\'"`]')
    found = [f'[`{p}`](../src/{p})' for p, text in plugins.items() if pattern.search(text)]
    found += [f'`{f}`' for f, text in legacy.items() if pattern.search(text)]
    return found

out = ['# Feature catalog\n', '\nEvery option on the Settings page and the code that reads it: plugin files under `src/plugins/` (see [PLUGINS.md](PLUGINS.md)), plus any legacy script that still reads it. Generated by `python3 scripts/features.py`.\n']
group = None
for row in parser.rows:
    if row['group'] == 'About TTV Tools' or not row['title']: continue
    if row['group'] != group:
        group = row['group']; out.append(f'\n## {group}\n\n| Feature | Settings | Read by |\n|---|---|---|\n')
    code = []
    for key in row['ids']:
        for r in readers(key):
            if r not in code: code.append(r)
    keys = ', '.join(f'`{k}`' for k in row['ids'][:6]) + (' …' if len(row['ids']) > 6 else '')
    new = f" <sub>since {row['new']}</sub>" if row['new'] else ''
    out.append(f"| {row['title']}{new} | {keys} | {'<br>'.join(code[:6]) or '—'} |\n")
open('docs/FEATURES.md', 'w', encoding='utf8').write(''.join(out))
print('wrote docs/FEATURES.md,', sum(1 for r in parser.rows if r['title']), 'features')
