/*** /plugins/index.js
 * Every plugin, in the order they start. Add new plugins here.
 */

import './automation/auto-join.js';
import './automation/kill-extensions.js';
import './automation/view-mode.js';
import './automation/claim-loot.js';
import './automation/claim-prime.js';
import './automation/claim-drops.js';
import './automation/first-in-line-plus.js';
import './customization/store-integration.js';
import './automation/parse-commands.js';
import './automation/auto-badge.js';
import './automation/prevent-raiding.js';
import './automation/greedy-raiding.js';
import './automation/stay-live.js';
import './automation/time-zones.js';
import './customization/block-banners.js';
import './customization/point-watcher.js';
import './video-recovery/recover-frames.js';
import './video-recovery/recover-stream.js';
import './video-recovery/recover-video.js';
import './video-recovery/user-intent.js';
import './video-recovery/private-viewing.js';
import './video-recovery/recover-pages.js';
import './misc/miscellaneous.js';
import './automation/not-implemented.js';
import './automation/auto-focus.js';
import './automation/lurking.js';
import './automation/claim-reward.js';
import './up-next/helpers.js';
import './up-next/first-in-line.js';
import './automation/live-reminders.js';
import './automation/auto-follow.js';
import './notifications/notification-sounds.js';
import './notifications/mention-audio.js';
import './notifications/phrase-audio.js';
import './notifications/whisper-audio.js';
import './currencies/points-receipt.js';
import './customization/stream-preview.js';
import './customization/watch-time.js';
import './networking/auto-dvr.js';
import './developer/developer-features.js';
